# Generated by Django 4.2.16 on 2024-12-08 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('speciality', 'title')},
        ),
        migrations.RemoveField(
            model_name='service',
            name='doctor',
        ),
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Доктор'),
        ),
    ]
