# Generated by Django 4.2.16 on 2024-12-01 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_rename_doctors_id_service_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ManyToManyField(limit_choices_to={'role': 'Doctor'}, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Доктор'),
        ),
    ]
