# Generated by Django 4.2.16 on 2024-12-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_doctor_id_service_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='doctor',
            new_name='doctor_id',
        ),
    ]
