# Generated by Django 4.2.16 on 2024-12-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
        ('service', '0003_alter_service_unique_together_remove_service_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='speciality',
        ),
        migrations.AddField(
            model_name='service',
            name='speciality',
            field=models.ManyToManyField(blank=True, related_name='speciality', to='speciality.speciality', verbose_name='Специализация'),
        ),
    ]
