# Generated by Django 4.2.16 on 2024-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=996, max_length=15, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
