# Generated by Django 5.1.3 on 2024-11-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
