# Generated by Django 4.2.16 on 2024-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
        ('authUser', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='speciality.speciality', verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
