# Generated by Django 4.2.16 on 2024-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_alter_customuser_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация'),
        ),
    ]
