# Generated by Django 4.2.16 on 2024-12-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
        ('authUser', '0006_alter_customuser_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_speciality', to='speciality.speciality', verbose_name='Специализация'),
        ),
    ]
