# Generated by Django 4.2.16 on 2024-12-16 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('work_end_time', models.TimeField(verbose_name='Конец рабочего дня')),
                ('lunch_start_time', models.TimeField(verbose_name='Начало обеда')),
                ('lunch_end_time', models.TimeField(verbose_name='Конец обеда')),
                ('break_start_time', models.TimeField(verbose_name='Начало полдника')),
                ('break_end_time', models.TimeField(verbose_name='Конец полдника')),
            ],
            options={
                'verbose_name': 'Часы работы клиники',
                'verbose_name_plural': 'Часы работы клиники',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_visit', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='День приема')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status_of_appointment', models.CharField(choices=[('WAITING', 'Ожидание'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен'), ('EXPIRED', 'Выгоревший')], default='WAITING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(verbose_name='Цена')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Доктор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
