# Generated by Django 4.2.16 on 2024-12-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorworkingtime_timetable_doctor_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorworkingtime',
            name='doctor',
        ),
    ]
