# Generated by Django 4.2.16 on 2024-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_doctorworkingtime_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.CharField(max_length=5, unique=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Часы для записи',
                'verbose_name_plural': 'Часы для записей',
            },
        ),
        migrations.AlterModelOptions(
            name='doctorworkingtime',
            options={'verbose_name': 'Часы работы доктора', 'verbose_name_plural': 'Часы работы докторов'},
        ),
    ]
