# Generated by Django 4.2.16 on 2024-12-10 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_alter_timetable_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='end_work',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_work',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='doctor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
