# Generated by Django 4.2.16 on 2024-12-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_remove_timetable_end_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_of_visit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='День приема'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('doctor', 'day_of_visit')},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='doctor',
        ),
        migrations.AddField(
            model_name='timetable',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
            preserve_default=False,
        ),
    ]
