# Generated by Django 4.2.16 on 2024-12-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_timetable_unique_together_clinictime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinictime',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='clinictime',
            name='doctor',
        ),
    ]
