# Generated by Django 4.2.16 on 2024-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_clinictime_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_of_appointment',
            field=models.CharField(choices=[('WAITING', 'Ожидание'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен'), ('EXPIRED', 'Выгоревший')], default='WAITING', max_length=20),
        ),
    ]
