# Generated by Django 4.2.7 on 2024-11-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
